### ISSUE TITLE
Fix routing permissions

### ISSUE THREAD

**Issue by StefanDywersant** [OpusCapita/acl#48]
Currently there are two invalid permissions (not reflected in routing's acl.json).

Those should be deleted:
- routing/write
- routing/routing-manage

Those should be added:
- routing/manage for admin

**Comment by kwierchris** [comment]
Are the changes in this PR still required?

**Comment by StefanDywersant** [comment]
That is not a PR yet, but yes - they are needed.

Routing has two resourceIds: routing/manage and routing/read.

The ones that are in acl right now are broken.

**Comment by denic** [comment]
@StefanDywersant Is this fixed now?

**Comment by StefanDywersant** [comment]
Yes, closing issue
