### ISSUE TITLE
Satisfy new use case: who has a specific permission ?

### ISSUE THREAD

**Issue by gr4per** [OpusCapita/acl#50]
Comes from IPA
Who has permission to some resourceGroup on a specific service and tenant ?
Use case is:
Select invoice approver
For that system shows all users who have invoice approving resourceGroup granted by any permission.

Problem:
Currently not easily solvable as permission api goes down roleId and that is not possible to provide in this use case.

Proposal
We could use /api/permissions and add resourceGroupId=&serviceId= as query parameters

**Comment by kwierchris** [comment]
Done
